CREATE LOGIN [IIS APPPOOL\TransactionAPI] FROM WINDOWS;

USE TransactionAppDB
CREATE USER [IIS APPPOOL\TransactionAPI] FOR LOGIN [IIS APPPOOL\TransactionAPI]

ALTER ROLE db_owner ADD MEMBER [IIS APPPOOL\TransactionAPI]